|                                  |                                                                                                                                                                                                                                                                                                                       |
| -------------------------        | -----------------------------------------------                                                                                                                                                                                                                                                                       |
| Lancer `SomeExcep`               | `throw(SomeExcep())`                                                                                                                                                                                                                                                                                                  |
| Relancer l'exception courante    | `rethrow()`                                                                                                                                                                                                                                                                                                           |
| Définir `NewExcep`               | `struct NewExcep <: Exception`<br>`    v::String`<br>`end`<br><br>`Base.showerror(io::IO, e::NewExcep) = print(io, "A problem with $(e.v)!")`<br><br>`throw(NewExcep("x"))`                                                                                                                                           |
| Lever une erreur avec un message | `error(msg)`                                                                                                                                                                                                                                                                                                          |
| Gérer les exceptions             | `try`<br>`    # quelque chose de dangereux`<br>`catch ex`<br>`    if isa(ex, SomeExcep)`<br>`        # gérer SomeExcep`<br>`    elseif isa(ex, AnotherExcep)`<br>`        # gérer AnotherExcep`<br>`    else`<br>`        # gérer les autres exceptions`<br>`    end`<br>`finally`<br>`    # fait dans tous les cas`<br>`end` |
